name: Build & Deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      # 👉 If this is a *project site*, set your repo name here:
      #    e.g. REPO_BASE="/your-repo-name/"
      #    If it's a user/org site, leave it as "/"
      - name: Set base href
        run: echo "REPO_BASE='/'" >> $GITHUB_ENV

      - name: Build (production)
        run: |
          if npm run | grep -q "^ *build"; then
            npm run build -- --configuration production --base-href "${REPO_BASE}" || \
            npm run build -- --base-href "${REPO_BASE}" || \
            npm run build
          else
            npx ng build --configuration production --base-href "${REPO_BASE}"
          fi

      - name: Prepare site folder for Pages
        run: |
          set -e
          rm -rf site
          mkdir -p site
          if [ ! -d dist ]; then
            echo "No dist directory found"; ls -la; exit 1
          fi
          entries=(dist/*)
          if [ ${#entries[@]} -eq 1 ] && [ -d "${entries[0]}" ]; then
            cp -a "${entries[0]}/." site/
          else
            cp -a dist/. site/
          fi
          # SPA fallback: copy index.html to 404.html so deep links work
          cp site/index.html site/404.html || true
          # Disable Jekyll processing
          touch site/.nojekyll

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
